GET http://localhost:8000/api/v1/hello

###

POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
    "email":"user001@email.com",
    "password":"Gymbro123"
}

###

POST http://localhost:8000/api/v1/auth/signup
Content-Type: application/json

{
    "email":"user002@email.com",
    "password":"Gymbro123",
    "firstName":"User",
    "lastName":"002"
}

###

POST http://localhost:8000/api/v1/auth/refresh_token
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImp0aSI6ImUwZTQzZDQxLWRmYTMtNDQwZS1iNGIwLThkNWI3OTMyMTViYSIsImlhdCI6MTY3ODkwOTgwOCwiZXhwIjoxNjc4OTM4NjA4fQ.64aDSiK4OP-_b9JSU2G6ZBGpNTrxb9njcCmGjnUFOW4"
}

###