GET http://localhost:8000/api/v1/hello

###

POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
    "email":"user001@email.com",
    "password":"Gymbro123"
}

###

POST http://localhost:8000/api/v1/auth/signup
Content-Type: application/json

{
    "email":"user005@email.com",
    "password":"Gymbro123",
    "firstName":"User",
    "lastName":"005"
}

###

POST http://localhost:8000/api/v1/auth/refresh_token
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImp0aSI6ImJhY2JmNzFkLWRkYTAtNGRjNy1iMjk0LTViYzYzZGU1YzFlZSIsImlhdCI6MTY3ODkxNjk2NywiZXhwIjoxNjc4OTQ1NzY3fQ.stJ48w-bkCqwLZAy321_tdRHZ9o9QZN1yjO-PRwBK50"
}

###

POST http://localhost:8000/api/v1/auth/revoke_refresh_tokens
Content-Type: application/json

{
    "userId":"1"
}