GET http://localhost:8000/api/v1/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY3OTY4MTA0MywiZXhwIjoxNjc5NjgxMzQzfQ.ViiZ5v8zC0_YqOQzJKgAlG6mgKYGmV8_CmdTtcA6BfI

###

POST http://localhost:8000/api/v1/user/update_profile_picture
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY3OTY4MTA0MywiZXhwIjoxNjc5NjgxMzQzfQ.ViiZ5v8zC0_YqOQzJKgAlG6mgKYGmV8_CmdTtcA6BfI

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="profile_picture"; filename="placeholder.jpg"
Content-Type: image/png

< ./placeholder.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###